$(document).ready(function() {
    $(".card1").hover(function(){
        $(".text1").css("visibility","hidden");
        $(".card-sub1").css("display","block");
    },function(){
        $(".text1").css("visibility","visible");
        $(".card-sub1").css("display","none");
    })
    $(".card2").hover(function(){
        $(".text2").css("visibility","hidden");
        $(".card-sub2").css("display","block");
    },function(){
        $(".text2").css("visibility","visible");
        $(".card-sub2").css("display","none");
    })
    $(".card3").hover(function(){
        $(".text3").css("visibility","hidden");
        $(".card-sub3").css("display","block");
    },function(){
        $(".text3").css("visibility","visible");
        $(".card-sub3").css("display","none");
    })
    $(".card4").hover(function(){
        $(".text4").css("visibility","hidden");
        $(".card-sub4").css("display","block");
    },function(){
        $(".text4").css("visibility","visible");
        $(".card-sub4").css("display","none");
    })
})

$(document).ready(function() {
    $("#card5").hover(function(){
        $("#cardtext1").css("display","block");
        $("#text1").css("visibility","hidden");
    },function(){
        $("#cardtext1").css("display","none");
        $("#text1").css("visibility","visible");
    })
    $("#card6").hover(function(){
        $("#cardtext2").css("display","block");
        $("#text2").css("visibility","hidden");
    },function(){
        $("#cardtext2").css("display","none");
        $("#text2").css("visibility","visible");
    })
    $("#card7").hover(function(){
        $("#cardtext3").css("display","block");
        $("#text3").css("visibility","hidden");
    },function(){
        $("#cardtext3").css("display","none");
        $("#text3").css("visibility","visible");
    })
    $("#card8").hover(function(){
        $("#cardtext4").css("display","block");
        $("#text4").css("visibility","hidden");
    },function(){
        $("#cardtext4").css("display","none");
        $("#text4").css("visibility","visible");
    })
})

$(document).ready(function() {
    $("#cardsub2").hover(function(){
        $("#cardsub1").css("background-color","var(--color-drkr-gray)");
        $("#cardsub1").css("color","var(--color-black)");
        $("#cardsub2").css("background-color","var(--color-blue)");
        $("#cardsub2").css("color","var(--color-white)");
    },function(){
        $("#cardsub1").css("background-color","var(--color-blue)");
        $("#cardsub1").css("color","var(--color-white)");
        $("#cardsub2").css("background-color","var(--color-drkr-gray)");
        $("#cardsub2").css("color","var(--color-black)");
    })
    $("#cardsub3").hover(function(){
        $("#cardsub1").css("background-color","var(--color-drkr-gray)");
        $("#cardsub1").css("color","var(--color-black)");
        $("#cardsub2").css("background-color","var(--color-drkr-gray)");
        $("#cardsub2").css("color","var(--color-black)");
        $("#cardsub3").css("background-color","var(--color-blue)");
        $("#cardsub3").css("color","var(--color-white)");
    },function(){
        $("#cardsub1").css("background-color","var(--color-blue)");
        $("#cardsub1").css("color","var(--color-white)");
        $("#cardsub3").css("background-color","var(--color-drkr-gray)");
        $("#cardsub3").css("color","var(--color-black)");
    })
    $("#cardsub4").hover(function(){
        $("#cardsub1").css("background-color","var(--color-drkr-gray)");
        $("#cardsub1").css("color","var(--color-black)");
        $("#cardsub2").css("background-color","var(--color-drkr-gray)");
        $("#cardsub2").css("color","var(--color-black)");
        $("#cardsub3").css("background-color","var(--color-drkr-gray)");
        $("#cardsub3").css("color","var(--color-black)");
        $("#cardsub4").css("background-color","var(--color-blue)");
        $("#cardsub4").css("color","var(--color-white)");
    },function(){
        $("#cardsub1").css("background-color","var(--color-blue)");
        $("#cardsub1").css("color","var(--color-white)");
        $("#cardsub4").css("background-color","var(--color-drkr-gray)");
        $("#cardsub4").css("color","var(--color-black)");
    })
    $("#cardsub5").hover(function(){
        $("#cardsub1").css("background-color","var(--color-drkr-gray)");
        $("#cardsub1").css("color","var(--color-black)");
        $("#cardsub2").css("background-color","var(--color-drkr-gray)");
        $("#cardsub2").css("color","var(--color-black)");
        $("#cardsub3").css("background-color","var(--color-drkr-gray)");
        $("#cardsub3").css("color","var(--color-black)");
        $("#cardsub4").css("background-color","var(--color-drkr-gray)");
        $("#cardsub4").css("color","var(--color-black)");
        $("#cardsub5").css("background-color","var(--color-blue)");
        $("#cardsub5").css("color","var(--color-white)");
    },function(){
        $("#cardsub1").css("background-color","var(--color-blue)");
        $("#cardsub1").css("color","var(--color-white)");
        $("#cardsub5").css("background-color","var(--color-drkr-gray)");
        $("#cardsub5").css("color","var(--color-black)");
    })
})

$(document).ready(function() {
    $("#cardsubtext1").click(function(){
        $("#cardsubtext1").css("background-color","var(--color-blue)");
        $("#cardsubtext1").css("color","var(--color-white)");
        $("#cardsubtext2").css("background-color","var(--color-drkr-gray)");
        $("#cardsubtext2").css("color","var(--color-black)");
    })
    $("#cardsubtext2").click(function(){
        $("#cardsubtext2").css("background-color","var(--color-blue)");
        $("#cardsubtext2").css("color","var(--color-white)");
        $("#cardsubtext1").css("background-color","var(--color-drkr-gray)");
        $("#cardsubtext1").css("color","var(--color-black)");
    })
})

$(document).ready(function() {
    $("#cardbox1").hover(function(){
        $("#cardboxtext1").css("visibility","visible");
        $("#cardboxtext1").css("background-color","var(--color-white)");
        $("#cardboxtext1").css("color","var(--color-black)");
        $("#cardboxtext1").css("border-radius","0.8rem");
        $("#cardboxtext1").css("opacity","60%");
        $("#cardboxtext1").css("animation","compload2 0.8s ease-in-out");
    },function(){
        $("#cardboxtext1").css("visibility","hidden");
        $("#cardboxtext1").css("animation","none");
    })
    $("#cardbox2").hover(function(){
        $("#cardboxtext2").css("visibility","visible");
        $("#cardboxtext2").css("background-color","var(--color-white)");
        $("#cardboxtext2").css("color","var(--color-black)");
        $("#cardboxtext2").css("border-radius","0.8rem");
        $("#cardboxtext2").css("opacity","60%");
        $("#cardboxtext2").css("animation","compload2 0.8s ease-in-out");
    },function(){
        $("#cardboxtext2").css("visibility","hidden");
        $("#cardboxtext2").css("animation","none");
    })
    $("#cardbox3").hover(function(){
        $("#cardboxtext3").css("visibility","visible");
        $("#cardboxtext3").css("background-color","var(--color-white)");
        $("#cardboxtext3").css("color","var(--color-black)");
        $("#cardboxtext3").css("border-radius","0.8rem");
        $("#cardboxtext3").css("opacity","60%");
        $("#cardboxtext3").css("animation","compload2 0.8s ease-in-out");
    },function(){
        $("#cardboxtext3").css("visibility","hidden");
        $("#cardboxtext3").css("animation","none");
    })
    $("#cardbox4").hover(function(){
        $("#cardboxtext4").css("visibility","visible");
        $("#cardboxtext4").css("background-color","var(--color-white)");
        $("#cardboxtext4").css("color","var(--color-black)");
        $("#cardboxtext4").css("border-radius","0.8rem");
        $("#cardboxtext4").css("opacity","60%");
        $("#cardboxtext4").css("animation","compload2 0.8s ease-in-out");
    },function(){
        $("#cardboxtext4").css("visibility","hidden");
        $("#cardboxtext4").css("animation","none");
    })
    $("#cardbox5").hover(function(){
        $("#cardboxtext5").css("visibility","visible");
        $("#cardboxtext5").css("background-color","var(--color-white)");
        $("#cardboxtext5").css("color","var(--color-black)");
        $("#cardboxtext5").css("border-radius","0.8rem");
        $("#cardboxtext5").css("opacity","60%");
        $("#cardboxtext5").css("animation","compload2 0.8s ease-in-out");
    },function(){
        $("#cardboxtext5").css("visibility","hidden");
        $("#cardboxtext5").css("animation","none");
    })
    $("#cardbox6").hover(function(){
        $("#cardboxtext6").css("visibility","visible");
        $("#cardboxtext6").css("background-color","var(--color-white)");
        $("#cardboxtext6").css("color","var(--color-black)");
        $("#cardboxtext6").css("border-radius","0.8rem");
        $("#cardboxtext6").css("opacity","60%");
        $("#cardboxtext6").css("animation","compload2 0.8s ease-in-out");
    },function(){
        $("#cardboxtext6").css("visibility","hidden");
        $("#cardboxtext6").css("animation","none");
    })
    $("#cardbox7").hover(function(){
        $("#cardboxtext7").css("visibility","visible");
        $("#cardboxtext7").css("background-color","var(--color-white)");
        $("#cardboxtext7").css("color","var(--color-black)");
        $("#cardboxtext7").css("border-radius","0.8rem");
        $("#cardboxtext7").css("opacity","60%");
        $("#cardboxtext7").css("animation","compload2 0.8s ease-in-out");
    },function(){
        $("#cardboxtext7").css("visibility","hidden");
        $("#cardboxtext7").css("animation","none");
    })
    $("#cardbox8").hover(function(){
        $("#cardboxtext8").css("visibility","visible");
        $("#cardboxtext8").css("background-color","var(--color-white)");
        $("#cardboxtext8").css("color","var(--color-black)");
        $("#cardboxtext8").css("border-radius","0.8rem");
        $("#cardboxtext8").css("opacity","60%");
        $("#cardboxtext8").css("animation","compload2 0.8s ease-in-out");
    },function(){
        $("#cardboxtext8").css("visibility","hidden");
        $("#cardboxtext8").css("animation","none");
    })
})

$(document).ready(function() {
    $("#cardsubtext1").click(function(){
        $(".cardgroupbox1").css("display","inline-block");
        $(".cardgroupbox2").css("display","none");
    })
    $("#cardsubtext2").click(function(){
        $(".cardgroupbox2").css("display","inline-block");
        $(".cardgroupbox1").css("display","none");
    })
})

// To hide & show the texts on icon hover
$(document).ready(function() {
    $(".iconlnkdn").hover(function(){
        $("#textTitle1").css("display","block");
    },function(){
        $("#textTitle1").css("display","none");
    })
    $(".iconfb").hover(function(){
        $("#textTitle2").css("display","block");
    },function(){
        $("#textTitle2").css("display","none");
    })
    $(".iconutube").hover(function(){
        $("#textTitle3").css("display","block");
    },function(){
        $("#textTitle3").css("display","none");
    })
    $(".icontwtr").hover(function(){
        $("#textTitle4").css("display","block");
    },function(){
        $("#textTitle4").css("display","none");
    })
})